version: '3'

services:
  oracle:
    image: absolutapps/oracle-12c-ee
    ports:
      - '1521:1521'
      - '5500:5500'
      - '8080:8080'
    container_name: oracle
    volumes:
      - db-data:/u01/app/oracle/oradata

volumes:
  db-data:

networks:
  dev:
