import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUser1604435608820 implements MigrationInterface {
  name = 'CreateUser1604435608820';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "user" ("id" number GENERATED BY DEFAULT AS IDENTITY, "firstName" varchar2(255) NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user"`);
  }
}
